# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63b4f62315e5e7714172b5ccee4c1cb7987b83cc9807545e27146bb56ea82e345449e09681869b305c39187a3d96a56e48d7ed7f97747ae601a9e5ed8d6a1df4

test:
  secret_key_base: e0c47efcf29be247913bffcb69b45f1f6d41bb62dd5f3d34845e53636b841e7eb6ffc0222e65184f682a8dff95b6ed9010867e756375751f7fa44976064d24f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
